// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _AudioModulatorMessageData {
  GObject parent_instance;

  gchar* name;
  gchar* description;
  AudioModulatorCode code;
  FlValue* data;
};

G_DEFINE_TYPE(AudioModulatorMessageData, audio_modulator_message_data, G_TYPE_OBJECT)

static void audio_modulator_message_data_dispose(GObject* object) {
  AudioModulatorMessageData* self = AUDIO_MODULATOR_MESSAGE_DATA(object);
  g_clear_pointer(&self->name, g_free);
  g_clear_pointer(&self->description, g_free);
  g_clear_pointer(&self->data, fl_value_unref);
  G_OBJECT_CLASS(audio_modulator_message_data_parent_class)->dispose(object);
}

static void audio_modulator_message_data_init(AudioModulatorMessageData* self) {
}

static void audio_modulator_message_data_class_init(AudioModulatorMessageDataClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = audio_modulator_message_data_dispose;
}

AudioModulatorMessageData* audio_modulator_message_data_new(const gchar* name, const gchar* description, AudioModulatorCode code, FlValue* data) {
  AudioModulatorMessageData* self = AUDIO_MODULATOR_MESSAGE_DATA(g_object_new(audio_modulator_message_data_get_type(), nullptr));
  if (name != nullptr) {
    self->name = g_strdup(name);
  }
  else {
    self->name = nullptr;
  }
  if (description != nullptr) {
    self->description = g_strdup(description);
  }
  else {
    self->description = nullptr;
  }
  self->code = code;
  self->data = fl_value_ref(data);
  return self;
}

const gchar* audio_modulator_message_data_get_name(AudioModulatorMessageData* self) {
  g_return_val_if_fail(AUDIO_MODULATOR_IS_MESSAGE_DATA(self), nullptr);
  return self->name;
}

const gchar* audio_modulator_message_data_get_description(AudioModulatorMessageData* self) {
  g_return_val_if_fail(AUDIO_MODULATOR_IS_MESSAGE_DATA(self), nullptr);
  return self->description;
}

AudioModulatorCode audio_modulator_message_data_get_code(AudioModulatorMessageData* self) {
  g_return_val_if_fail(AUDIO_MODULATOR_IS_MESSAGE_DATA(self), static_cast<AudioModulatorCode>(0));
  return self->code;
}

FlValue* audio_modulator_message_data_get_data(AudioModulatorMessageData* self) {
  g_return_val_if_fail(AUDIO_MODULATOR_IS_MESSAGE_DATA(self), nullptr);
  return self->data;
}

static FlValue* audio_modulator_message_data_to_list(AudioModulatorMessageData* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, self->name != nullptr ? fl_value_new_string(self->name) : fl_value_new_null());
  fl_value_append_take(values, self->description != nullptr ? fl_value_new_string(self->description) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_custom(129, fl_value_new_int(self->code), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_ref(self->data));
  return values;
}

static AudioModulatorMessageData* audio_modulator_message_data_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* name = nullptr;
  if (fl_value_get_type(value0) != FL_VALUE_TYPE_NULL) {
    name = fl_value_get_string(value0);
  }
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* description = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    description = fl_value_get_string(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  AudioModulatorCode code = static_cast<AudioModulatorCode>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value2)))));
  FlValue* value3 = fl_value_get_list_value(values, 3);
  FlValue* data = value3;
  return audio_modulator_message_data_new(name, description, code, data);
}

struct _AudioModulatorMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(AudioModulatorMessageCodec, audio_modulator_message_codec, fl_standard_message_codec_get_type())

static gboolean audio_modulator_message_codec_write_audio_modulator_code(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 129;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean audio_modulator_message_codec_write_audio_modulator_message_data(FlStandardMessageCodec* codec, GByteArray* buffer, AudioModulatorMessageData* value, GError** error) {
  uint8_t type = 130;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = audio_modulator_message_data_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean audio_modulator_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case 129:
        return audio_modulator_message_codec_write_audio_modulator_code(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 130:
        return audio_modulator_message_codec_write_audio_modulator_message_data(codec, buffer, AUDIO_MODULATOR_MESSAGE_DATA(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(audio_modulator_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* audio_modulator_message_codec_read_audio_modulator_code(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(129, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* audio_modulator_message_codec_read_audio_modulator_message_data(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(AudioModulatorMessageData) value = audio_modulator_message_data_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(130, G_OBJECT(value));
}

static FlValue* audio_modulator_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case 129:
      return audio_modulator_message_codec_read_audio_modulator_code(codec, buffer, offset, error);
    case 130:
      return audio_modulator_message_codec_read_audio_modulator_message_data(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(audio_modulator_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void audio_modulator_message_codec_init(AudioModulatorMessageCodec* self) {
}

static void audio_modulator_message_codec_class_init(AudioModulatorMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = audio_modulator_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = audio_modulator_message_codec_read_value_of_type;
}

static AudioModulatorMessageCodec* audio_modulator_message_codec_new() {
  AudioModulatorMessageCodec* self = AUDIO_MODULATOR_MESSAGE_CODEC(g_object_new(audio_modulator_message_codec_get_type(), nullptr));
  return self;
}

struct _AudioModulatorExampleHostApiPlayAudioResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(AudioModulatorExampleHostApiPlayAudioResponse, audio_modulator_example_host_api_play_audio_response, G_TYPE_OBJECT)

static void audio_modulator_example_host_api_play_audio_response_dispose(GObject* object) {
  AudioModulatorExampleHostApiPlayAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_PLAY_AUDIO_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(audio_modulator_example_host_api_play_audio_response_parent_class)->dispose(object);
}

static void audio_modulator_example_host_api_play_audio_response_init(AudioModulatorExampleHostApiPlayAudioResponse* self) {
}

static void audio_modulator_example_host_api_play_audio_response_class_init(AudioModulatorExampleHostApiPlayAudioResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = audio_modulator_example_host_api_play_audio_response_dispose;
}

AudioModulatorExampleHostApiPlayAudioResponse* audio_modulator_example_host_api_play_audio_response_new() {
  AudioModulatorExampleHostApiPlayAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_PLAY_AUDIO_RESPONSE(g_object_new(audio_modulator_example_host_api_play_audio_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

AudioModulatorExampleHostApiPlayAudioResponse* audio_modulator_example_host_api_play_audio_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  AudioModulatorExampleHostApiPlayAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_PLAY_AUDIO_RESPONSE(g_object_new(audio_modulator_example_host_api_play_audio_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _AudioModulatorExampleHostApiStopAudioResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(AudioModulatorExampleHostApiStopAudioResponse, audio_modulator_example_host_api_stop_audio_response, G_TYPE_OBJECT)

static void audio_modulator_example_host_api_stop_audio_response_dispose(GObject* object) {
  AudioModulatorExampleHostApiStopAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_STOP_AUDIO_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(audio_modulator_example_host_api_stop_audio_response_parent_class)->dispose(object);
}

static void audio_modulator_example_host_api_stop_audio_response_init(AudioModulatorExampleHostApiStopAudioResponse* self) {
}

static void audio_modulator_example_host_api_stop_audio_response_class_init(AudioModulatorExampleHostApiStopAudioResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = audio_modulator_example_host_api_stop_audio_response_dispose;
}

AudioModulatorExampleHostApiStopAudioResponse* audio_modulator_example_host_api_stop_audio_response_new() {
  AudioModulatorExampleHostApiStopAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_STOP_AUDIO_RESPONSE(g_object_new(audio_modulator_example_host_api_stop_audio_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

AudioModulatorExampleHostApiStopAudioResponse* audio_modulator_example_host_api_stop_audio_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  AudioModulatorExampleHostApiStopAudioResponse* self = AUDIO_MODULATOR_EXAMPLE_HOST_API_STOP_AUDIO_RESPONSE(g_object_new(audio_modulator_example_host_api_stop_audio_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _AudioModulatorExampleHostApi {
  GObject parent_instance;

  const AudioModulatorExampleHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(AudioModulatorExampleHostApi, audio_modulator_example_host_api, G_TYPE_OBJECT)

static void audio_modulator_example_host_api_dispose(GObject* object) {
  AudioModulatorExampleHostApi* self = AUDIO_MODULATOR_EXAMPLE_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(audio_modulator_example_host_api_parent_class)->dispose(object);
}

static void audio_modulator_example_host_api_init(AudioModulatorExampleHostApi* self) {
}

static void audio_modulator_example_host_api_class_init(AudioModulatorExampleHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = audio_modulator_example_host_api_dispose;
}

static AudioModulatorExampleHostApi* audio_modulator_example_host_api_new(const AudioModulatorExampleHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  AudioModulatorExampleHostApi* self = AUDIO_MODULATOR_EXAMPLE_HOST_API(g_object_new(audio_modulator_example_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void audio_modulator_example_host_api_play_audio_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  AudioModulatorExampleHostApi* self = AUDIO_MODULATOR_EXAMPLE_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->play_audio == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* path = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  double pitch = fl_value_get_float(value1);
  FlValue* value2 = fl_value_get_list_value(message_, 2);
  int64_t speed = fl_value_get_int(value2);
  g_autoptr(AudioModulatorExampleHostApiPlayAudioResponse) response = self->vtable->play_audio(path, pitch, speed, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "ExampleHostApi", "playAudio");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "ExampleHostApi", "playAudio", error->message);
  }
}

static void audio_modulator_example_host_api_stop_audio_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  AudioModulatorExampleHostApi* self = AUDIO_MODULATOR_EXAMPLE_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->stop_audio == nullptr) {
    return;
  }

  g_autoptr(AudioModulatorExampleHostApiStopAudioResponse) response = self->vtable->stop_audio(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "ExampleHostApi", "stopAudio");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "ExampleHostApi", "stopAudio", error->message);
  }
}

void audio_modulator_example_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const AudioModulatorExampleHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(AudioModulatorExampleHostApi) api_data = audio_modulator_example_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(AudioModulatorMessageCodec) codec = audio_modulator_message_codec_new();
  g_autofree gchar* play_audio_channel_name = g_strdup_printf("dev.flutter.pigeon.audio_modulator.ExampleHostApi.playAudio%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) play_audio_channel = fl_basic_message_channel_new(messenger, play_audio_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(play_audio_channel, audio_modulator_example_host_api_play_audio_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* stop_audio_channel_name = g_strdup_printf("dev.flutter.pigeon.audio_modulator.ExampleHostApi.stopAudio%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_audio_channel = fl_basic_message_channel_new(messenger, stop_audio_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_audio_channel, audio_modulator_example_host_api_stop_audio_cb, g_object_ref(api_data), g_object_unref);
}

void audio_modulator_example_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(AudioModulatorMessageCodec) codec = audio_modulator_message_codec_new();
  g_autofree gchar* play_audio_channel_name = g_strdup_printf("dev.flutter.pigeon.audio_modulator.ExampleHostApi.playAudio%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) play_audio_channel = fl_basic_message_channel_new(messenger, play_audio_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(play_audio_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* stop_audio_channel_name = g_strdup_printf("dev.flutter.pigeon.audio_modulator.ExampleHostApi.stopAudio%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_audio_channel = fl_basic_message_channel_new(messenger, stop_audio_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_audio_channel, nullptr, nullptr, nullptr);
}
